<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class DashboardController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request): Response
    {
        $projects = [
            [
                'id' => 1,
                'name' => 'Project 1',
                'rowCount' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Project 2',
                'rowCount' => 1,
            ],
            [
                'id' => 3,
                'name' => 'Project 3',
                'rowCount' => 1,
            ],
        ];

        $tasks = [
            // PROJECT: 1
            // Stage: DVM
            [
                'id' => '1',
                'name' => 'DVM',
                'start' => '2024-10-01',
                'end' => '2024-11-10',
                'dependencies' => [],
                'children' => ['100', '101', '102', '103'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '100',
                'name' => 'Initial Planning',
                'start' => '2024-10-01',
                'end' => '2024-10-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
            ],
            [
                'id' => '101',
                'name' => 'Documentation Review',
                'start' => '2024-10-06',
                'end' => '2024-10-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
            ],
            [
                'id' => '102',
                'name' => 'Approval Meeting',
                'start' => '2024-10-11',
                'end' => '2024-10-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
            ],
            [
                'id' => '103',
                'name' => 'Final Approval',
                'start' => '2024-10-16',
                'end' => '2024-10-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
            ],

// Stage: Lease
            [
                'id' => '2',
                'name' => 'Lease',
                'start' => '2024-11-15',
                'end' => '2024-12-15',
                'progress' => 50,
                'dependencies' => '',
                'children' => ['200', '201', '202', '203'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '200',
                'name' => 'Site Evaluation',
                'start' => '2024-11-15',
                'end' => '2024-11-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],
            [
                'id' => '201',
                'name' => 'Legal Review',
                'start' => '2024-11-21',
                'end' => '2024-11-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],
            [
                'id' => '202',
                'name' => 'Negotiation',
                'start' => '2024-11-26',
                'end' => '2024-11-30',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],
            [
                'id' => '203',
                'name' => 'Lease Signing',
                'start' => '2024-12-01',
                'end' => '2024-12-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],

// Stage: Permit
            [
                'id' => '3',
                'name' => 'Permit',
                'start' => '2024-12-18',
                'end' => '2025-01-10',
                'dependencies' => [],
                'children' => ['300', '301', '302'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '300',
                'name' => 'Permit Application',
                'start' => '2024-12-20',
                'end' => '2024-12-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '3',
            ],
            [
                'id' => '301',
                'name' => 'Review Process',
                'start' => '2024-12-26',
                'end' => '2024-12-30',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '3',
            ],
            [
                'id' => '302',
                'name' => 'Permit Approval',
                'start' => '2025-01-02',
                'end' => '2025-01-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '3',
            ],

// Stage: Construction
            [
                'id' => '4',
                'name' => 'Construction',
                'start' => '2025-01-15',
                'end' => '2025-04-15',
                'dependencies' => [],
                'children' => ['400', '401', '402', '403', '404'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '400',
                'name' => 'Site Preparation',
                'start' => '2025-01-16',
                'end' => '2025-01-31',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '401',
                'name' => 'Foundation Work',
                'start' => '2025-02-01',
                'end' => '2025-02-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '402',
                'name' => 'Framing',
                'start' => '2025-02-11',
                'end' => '2025-02-28',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '403',
                'name' => 'Roof Installation',
                'start' => '2025-03-01',
                'end' => '2025-03-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '404',
                'name' => 'Exterior Finishing',
                'start' => '2025-03-11',
                'end' => '2025-03-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],

// Stage: Opening
            [
                'id' => '5',
                'name' => 'Opening',
                'start' => '2025-05-01',
                'end' => '2025-05-15',
                'dependencies' => [],
                'children' => ['500', '501', '502'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '500',
                'name' => 'Final Inspection',
                'start' => '2025-05-02',
                'end' => '2025-05-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '5',
            ],
            [
                'id' => '501',
                'name' => 'Staff Training',
                'start' => '2025-05-06',
                'end' => '2025-05-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '5',
            ],
            [
                'id' => '502',
                'name' => 'Grand Opening Preparation',
                'start' => '2025-05-11',
                'end' => '2025-05-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '5',
            ],

            // PROJECT: 2

// Stage: DVM
            [
                'id' => '10',
                'name' => 'DVM',
                'start' => '2024-10-01',
                'end' => '2024-11-10',
                'dependencies' => [],
                'children' => ['110', '111'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '110',
                'name' => 'Initial Analysis',
                'start' => '2024-10-01',
                'end' => '2024-10-04',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '10',
            ],
            [
                'id' => '111',
                'name' => 'Technical Review',
                'start' => '2024-10-05',
                'end' => '2024-10-08',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '10',
            ],

// Stage: Lease
            [
                'id' => '20',
                'name' => 'Lease',
                'start' => '2024-11-15',
                'end' => '2024-12-15',
                'progress' => 50,
                'dependencies' => '',
                'children' => ['210'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '210',
                'name' => 'Lease Review',
                'start' => '2024-11-15',
                'end' => '2024-11-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '20',
            ],

// Stage: Permit
            [
                'id' => '30',
                'name' => 'Permit',
                'start' => '2024-12-18',
                'end' => '2025-01-10',
                'dependencies' => [],
                'children' => ['310', '311'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '310',
                'name' => 'Permit Submission',
                'start' => '2024-12-20',
                'end' => '2024-12-24',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '30',
            ],
            [
                'id' => '311',
                'name' => 'Feedback Review',
                'start' => '2024-12-25',
                'end' => '2024-12-28',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '30',
            ],

// Stage: Construction
            [
                'id' => '40',
                'name' => 'Construction',
                'start' => '2025-01-15',
                'end' => '2025-04-15',
                'dependencies' => [],
                'children' => ['410', '411'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '410',
                'name' => 'Initial Setup',
                'start' => '2025-01-16',
                'end' => '2025-01-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '40',
            ],
            [
                'id' => '411',
                'name' => 'Material Procurement',
                'start' => '2025-01-26',
                'end' => '2025-02-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '40',
            ],

// Stage: Opening
            [
                'id' => '50',
                'name' => 'Opening',
                'start' => '2025-05-01',
                'end' => '2025-05-15',
                'dependencies' => [],
                'children' => ['510'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '510',
                'name' => 'Soft Launch',
                'start' => '2025-05-10',
                'end' => '2025-05-12',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '50',
            ],

            // PROJECT: 3

            // Stage: DVM
            [
                'id' => '1001',
                'name' => 'DVM',
                'start' => '2024-10-01',
                'end' => '2024-11-10',
                'dependencies' => [],
                'children' => ['1002', '1003', '1004'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1002',
                'name' => 'Preliminary Research',
                'start' => '2024-10-01',
                'end' => '2024-10-03',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1001',
            ],
            [
                'id' => '1003',
                'name' => 'Requirement Gathering',
                'start' => '2024-10-04',
                'end' => '2024-10-07',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1001',
            ],
            [
                'id' => '1004',
                'name' => 'Approval Process',
                'start' => '2024-10-08',
                'end' => '2024-10-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1001',
            ],

// Stage: Lease
            [
                'id' => '1010',
                'name' => 'Lease',
                'start' => '2024-11-15',
                'end' => '2024-12-15',
                'progress' => 50,
                'dependencies' => '',
                'children' => ['1011', '1012'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1011',
                'name' => 'Lease Negotiation',
                'start' => '2024-11-15',
                'end' => '2024-11-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1010',
            ],
            [
                'id' => '1012',
                'name' => 'Document Signing',
                'start' => '2024-11-21',
                'end' => '2024-11-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1010',
            ],

// Stage: Permit
            [
                'id' => '1020',
                'name' => 'Permit',
                'start' => '2024-12-18',
                'end' => '2025-01-10',
                'dependencies' => [],
                'children' => ['1021', '1022'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1021',
                'name' => 'Permit Application',
                'start' => '2024-12-20',
                'end' => '2024-12-24',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1020',
            ],
            [
                'id' => '1022',
                'name' => 'Review Compliance',
                'start' => '2024-12-25',
                'end' => '2024-12-28',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1020',
            ],

// Stage: Construction
            [
                'id' => '1030',
                'name' => 'Construction',
                'start' => '2025-01-15',
                'end' => '2025-04-15',
                'dependencies' => [],
                'children' => ['1031', '1032', '1033'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1031',
                'name' => 'Site Preparation',
                'start' => '2025-01-16',
                'end' => '2025-01-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1030',
            ],
            [
                'id' => '1032',
                'name' => 'Foundation Work',
                'start' => '2025-01-26',
                'end' => '2025-02-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1030',
            ],
            [
                'id' => '1033',
                'name' => 'Framing',
                'start' => '2025-02-06',
                'end' => '2025-02-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1030',
            ],

// Stage: Opening
            [
                'id' => '1040',
                'name' => 'Opening',
                'start' => '2025-05-01',
                'end' => '2025-05-15',
                'dependencies' => [],
                'children' => ['1041', '1042'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1041',
                'name' => 'Final Inspection',
                'start' => '2025-05-10',
                'end' => '2025-05-12',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1040',
            ],
            [
                'id' => '1042',
                'name' => 'Opening Event',
                'start' => '2025-05-13',
                'end' => '2025-05-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1040',
            ],
        ];

        return Inertia::render('Dashboard', [
            'projects' => $projects,
            'tasks' => $tasks,
        ]);
    }
}
