<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class DashboardController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request): Response
    {
        $projects = [
            [
                'id' => '1',
                'name' => 'Project 1',
            ],
            [
                'id' => '2',
                'name' => 'Project 2',
            ],
            [
                'id' => '3',
                'name' => 'Project 3',
            ],
            [
                'id' => '4',
                'name' => 'Project 4',
            ],
            [
                'id' => '5',
                'name' => 'Project 5',
            ],
        ];

        $tasks = [
            // TODO: PROJECT: 1
            // Stage: DVM
            [
                'id' => '1',
                'name' => 'DVM',
                'start' => '2024-10-01',
                'end' => '2024-11-10',
                'dependencies' => [],
                'children' => ['100', '101', '102', '103'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '100',
                'name' => 'Initial Planning',
                'start' => '2024-10-01',
                'end' => '2024-10-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
            ],
            [
                'id' => '101',
                'name' => 'Documentation Review',
                'start' => '2024-10-06',
                'end' => '2024-10-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
            ],
            [
                'id' => '102',
                'name' => 'Approval Meeting',
                'start' => '2024-10-11',
                'end' => '2024-10-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
            ],
            [
                'id' => '103',
                'name' => 'Final Approval',
                'start' => '2024-10-16',
                'end' => '2024-10-16',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '1',
                'custom_class' => 'bar-milestone',
            ],

// Stage: Lease
            [
                'id' => '2',
                'name' => 'Lease',
                'start' => '2024-11-15',
                'end' => '2024-12-15',
                'progress' => 50,
                'dependencies' => '',
                'children' => ['200', '201', '202', '203'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '200',
                'name' => 'Site Evaluation',
                'start' => '2024-11-15',
                'end' => '2024-11-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],
            [
                'id' => '201',
                'name' => 'Legal Review',
                'start' => '2024-11-21',
                'end' => '2024-11-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],
            [
                'id' => '202',
                'name' => 'Negotiation',
                'start' => '2024-11-26',
                'end' => '2024-11-30',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],
            [
                'id' => '203',
                'name' => 'Lease Signing',
                'start' => '2024-12-01',
                'end' => '2024-12-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '2',
            ],

// Stage: Permit
            [
                'id' => '3',
                'name' => 'Permit',
                'start' => '2024-12-18',
                'end' => '2025-01-10',
                'dependencies' => [],
                'children' => ['300', '301', '302'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '300',
                'name' => 'Permit Application',
                'start' => '2024-12-20',
                'end' => '2024-12-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '3',
            ],
            [
                'id' => '301',
                'name' => 'Review Process',
                'start' => '2024-12-26',
                'end' => '2024-12-30',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '3',
            ],
            [
                'id' => '302',
                'name' => 'Permit Approval',
                'start' => '2025-01-02',
                'end' => '2025-01-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '3',
            ],

// Stage: Construction
            [
                'id' => '4',
                'name' => 'Construction',
                'start' => '2025-01-15',
                'end' => '2025-04-15',
                'dependencies' => [],
                'children' => ['400', '401', '402', '403', '404'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '400',
                'name' => 'Site Preparation',
                'start' => '2025-01-16',
                'end' => '2025-01-31',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '401',
                'name' => 'Foundation Work',
                'start' => '2025-02-01',
                'end' => '2025-02-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '402',
                'name' => 'Framing',
                'start' => '2025-02-11',
                'end' => '2025-02-28',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '403',
                'name' => 'Roof Installation',
                'start' => '2025-03-01',
                'end' => '2025-03-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],
            [
                'id' => '404',
                'name' => 'Exterior Finishing',
                'start' => '2025-03-11',
                'end' => '2025-03-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '4',
            ],

// Stage: Opening
            [
                'id' => '5',
                'name' => 'Opening',
                'start' => '2025-05-01',
                'end' => '2025-05-15',
                'dependencies' => [],
                'children' => ['500', '501', '502'],
                'display' => true,
                'project_id' => '1',
                'important' => true,
            ],
            [
                'id' => '500',
                'name' => 'Final Inspection',
                'start' => '2025-05-02',
                'end' => '2025-05-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '5',
            ],
            [
                'id' => '501',
                'name' => 'Staff Training',
                'start' => '2025-05-06',
                'end' => '2025-05-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '5',
            ],
            [
                'id' => '502',
                'name' => 'Grand Opening Preparation',
                'start' => '2025-05-11',
                'end' => '2025-05-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '1',
                'stage_id' => '5',
            ],

            // TODO: PROJECT: 2

// Stage: DVM
            [
                'id' => '10',
                'name' => 'DVM',
                'start' => '2024-10-01',
                'end' => '2024-11-10',
                'dependencies' => [],
                'children' => ['110', '111'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '110',
                'name' => 'Initial Analysis',
                'start' => '2024-10-01',
                'end' => '2024-10-04',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '10',
            ],
            [
                'id' => '111',
                'name' => 'Technical Review',
                'start' => '2024-10-05',
                'end' => '2024-10-08',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '10',
            ],

// Stage: Lease
            [
                'id' => '20',
                'name' => 'Lease',
                'start' => '2024-11-15',
                'end' => '2024-12-15',
                'progress' => 50,
                'dependencies' => '',
                'children' => ['210'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '210',
                'name' => 'Lease Review',
                'start' => '2024-11-15',
                'end' => '2024-11-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '20',
            ],

// Stage: Permit
            [
                'id' => '30',
                'name' => 'Permit',
                'start' => '2024-12-18',
                'end' => '2025-01-10',
                'dependencies' => [],
                'children' => ['310', '311'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '310',
                'name' => 'Permit Submission',
                'start' => '2024-12-20',
                'end' => '2024-12-24',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '30',
            ],
            [
                'id' => '311',
                'name' => 'Feedback Review',
                'start' => '2024-12-25',
                'end' => '2024-12-28',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '30',
            ],

// Stage: Construction
            [
                'id' => '40',
                'name' => 'Construction',
                'start' => '2025-01-15',
                'end' => '2025-04-15',
                'dependencies' => [],
                'children' => ['410', '411'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '410',
                'name' => 'Initial Setup',
                'start' => '2025-01-16',
                'end' => '2025-01-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '40',
            ],
            [
                'id' => '411',
                'name' => 'Material Procurement',
                'start' => '2025-01-26',
                'end' => '2025-02-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '40',
            ],

// Stage: Opening
            [
                'id' => '50',
                'name' => 'Opening',
                'start' => '2025-05-01',
                'end' => '2025-05-15',
                'dependencies' => [],
                'children' => ['510'],
                'display' => true,
                'project_id' => '2',
                'important' => true,
            ],
            [
                'id' => '510',
                'name' => 'Soft Launch',
                'start' => '2025-05-10',
                'end' => '2025-05-12',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '2',
                'stage_id' => '50',
            ],

            // TODO: PROJECT: 3

            // Stage: DVM
            [
                'id' => '1001',
                'name' => 'DVM',
                'start' => '2024-10-01',
                'end' => '2024-11-10',
                'dependencies' => [],
                'children' => ['1002', '1003', '1004'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1002',
                'name' => 'Preliminary Research',
                'start' => '2024-10-01',
                'end' => '2024-10-03',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1001',
            ],
            [
                'id' => '1003',
                'name' => 'Requirement Gathering',
                'start' => '2024-10-04',
                'end' => '2024-10-07',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1001',
            ],
            [
                'id' => '1004',
                'name' => 'Approval Process',
                'start' => '2024-10-08',
                'end' => '2024-10-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1001',
            ],

// Stage: Lease
            [
                'id' => '1010',
                'name' => 'Lease',
                'start' => '2024-11-15',
                'end' => '2024-12-15',
                'progress' => 50,
                'dependencies' => '',
                'children' => ['1011', '1012'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1011',
                'name' => 'Lease Negotiation',
                'start' => '2024-11-15',
                'end' => '2024-11-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1010',
            ],
            [
                'id' => '1012',
                'name' => 'Document Signing',
                'start' => '2024-11-21',
                'end' => '2024-11-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1010',
            ],

// Stage: Permit
            [
                'id' => '1020',
                'name' => 'Permit',
                'start' => '2024-12-18',
                'end' => '2025-01-10',
                'dependencies' => [],
                'children' => ['1021', '1022'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1021',
                'name' => 'Permit Application',
                'start' => '2024-12-20',
                'end' => '2024-12-24',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1020',
            ],
            [
                'id' => '1022',
                'name' => 'Review Compliance',
                'start' => '2024-12-25',
                'end' => '2024-12-28',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1020',
            ],

// Stage: Construction
            [
                'id' => '1030',
                'name' => 'Construction',
                'start' => '2025-01-15',
                'end' => '2025-04-15',
                'dependencies' => [],
                'children' => ['1031', '1032', '1033'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1031',
                'name' => 'Site Preparation',
                'start' => '2025-01-16',
                'end' => '2025-01-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1030',
            ],
            [
                'id' => '1032',
                'name' => 'Foundation Work',
                'start' => '2025-01-26',
                'end' => '2025-02-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1030',
            ],
            [
                'id' => '1033',
                'name' => 'Framing',
                'start' => '2025-02-06',
                'end' => '2025-02-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1030',
            ],

// Stage: Opening
            [
                'id' => '1040',
                'name' => 'Opening',
                'start' => '2025-05-01',
                'end' => '2025-05-15',
                'dependencies' => [],
                'children' => ['1041', '1042'],
                'display' => true,
                'project_id' => '3',
                'important' => true,
            ],
            [
                'id' => '1041',
                'name' => 'Final Inspection',
                'start' => '2025-05-10',
                'end' => '2025-05-12',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1040',
            ],
            [
                'id' => '1042',
                'name' => 'Opening Event',
                'start' => '2025-05-13',
                'end' => '2025-05-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '3',
                'stage_id' => '1040',
            ],

            // PROJECT: 4
            // Stage: DVM
            [
                'id' => '2000',
                'name' => 'DVM',
                'start' => '2024-10-01',
                'end' => '2024-11-10',
                'dependencies' => [],
                'children' => ['2001', '2002', '2003'],
                'display' => true,
                'project_id' => '4',
                'important' => true,
            ],
            [
                'id' => '2001',
                'name' => 'Risk Assessment',
                'start' => '2024-10-01',
                'end' => '2024-10-03',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2000',
            ],
            [
                'id' => '2002',
                'name' => 'Feasibility Analysis',
                'start' => '2024-10-04',
                'end' => '2024-10-07',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2000',
            ],
            [
                'id' => '2003',
                'name' => 'Stakeholder Approval',
                'start' => '2024-10-08',
                'end' => '2024-10-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2000',
            ],

            // Stage: Lease
            [
                'id' => '2010',
                'name' => 'Lease',
                'start' => '2024-11-15',
                'end' => '2024-12-15',
                'progress' => 50,
                'dependencies' => '',
                'children' => ['2011', '2012'],
                'display' => true,
                'project_id' => '4',
                'important' => true,
            ],
            [
                'id' => '2011',
                'name' => 'Initial Lease Review',
                'start' => '2024-11-15',
                'end' => '2024-11-20',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2010',
            ],
            [
                'id' => '2012',
                'name' => 'Final Lease Agreement',
                'start' => '2024-11-21',
                'end' => '2024-11-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2010',
            ],

            // Stage: Permit
            [
                'id' => '2020',
                'name' => 'Permit',
                'start' => '2024-12-18',
                'end' => '2025-01-10',
                'dependencies' => [],
                'children' => ['2021', '2022'],
                'display' => true,
                'project_id' => '4',
                'important' => true,
            ],
            [
                'id' => '2021',
                'name' => 'Application Submission',
                'start' => '2024-12-20',
                'end' => '2024-12-24',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2020',
            ],
            [
                'id' => '2022',
                'name' => 'Compliance Check',
                'start' => '2024-12-25',
                'end' => '2024-12-28',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2020',
            ],

            // Stage: Construction
            [
                'id' => '2030',
                'name' => 'Construction',
                'start' => '2025-01-15',
                'end' => '2025-04-15',
                'dependencies' => [],
                'children' => ['2031', '2032', '2033'],
                'display' => true,
                'project_id' => '4',
                'important' => true,
            ],
            [
                'id' => '2031',
                'name' => 'Excavation',
                'start' => '2025-01-16',
                'end' => '2025-01-25',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2030',
            ],
            [
                'id' => '2032',
                'name' => 'Concrete Pouring',
                'start' => '2025-01-26',
                'end' => '2025-02-05',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2030',
            ],
            [
                'id' => '2033',
                'name' => 'Structural Framing',
                'start' => '2025-02-06',
                'end' => '2025-02-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2030',
            ],

            // Stage: Opening
            [
                'id' => '2040',
                'name' => 'Opening',
                'start' => '2025-05-01',
                'end' => '2025-05-15',
                'dependencies' => [],
                'children' => ['2041', '2042'],
                'display' => true,
                'project_id' => '4',
                'important' => true,
            ],
            [
                'id' => '2041',
                'name' => 'Final Setup',
                'start' => '2025-05-10',
                'end' => '2025-05-12',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2040',
            ],
            [
                'id' => '2042',
                'name' => 'Public Opening Event',
                'start' => '2025-05-13',
                'end' => '2025-05-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '4',
                'stage_id' => '2040',
            ],

            // PROJECT: 5

            // Stage: DVM
            [
                'id' => '4000',
                'name' => 'DVM',
                'start' => '2024-12-01',
                'end' => '2024-12-15',
                'dependencies' => [],
                'children' => ['4001', '4002', '4003'],
                'display' => true,
                'project_id' => '5',
                'important' => true,
            ],
            [
                'id' => '4001',
                'name' => 'Site Assessment',
                'start' => '2024-12-01',
                'end' => '2024-12-03',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4000',
            ],
            [
                'id' => '4002',
                'name' => 'Initial Design',
                'start' => '2024-12-04',
                'end' => '2024-12-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4000',
            ],
            [
                'id' => '4003',
                'name' => 'Cost Estimation',
                'start' => '2024-12-11',
                'end' => '2024-12-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4000',
            ],

            // Stage: LEASE
            [
                'id' => '4004',
                'name' => 'LEASE',
                'start' => '2025-01-01',
                'end' => '2025-01-15',
                'dependencies' => ['4003'],
                'children' => ['4005', '4006'],
                'display' => true,
                'project_id' => '5',
                'important' => true,
            ],
            [
                'id' => '4005',
                'name' => 'Lease Negotiation',
                'start' => '2025-01-01',
                'end' => '2025-01-07',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4004',
            ],
            [
                'id' => '4006',
                'name' => 'Lease Signing',
                'start' => '2025-01-08',
                'end' => '2025-01-15',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4004',
            ],

            // Stage: PERMIT
            [
                'id' => '4007',
                'name' => 'PERMIT',
                'start' => '2025-02-01',
                'end' => '2025-02-28',
                'dependencies' => ['4006'],
                'children' => ['4008', '4009'],
                'display' => true,
                'project_id' => '5',
                'important' => true,
            ],
            [
                'id' => '4008',
                'name' => 'Permit Application',
                'start' => '2025-02-01',
                'end' => '2025-02-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4007',
            ],
            [
                'id' => '4009',
                'name' => 'Permit Approval',
                'start' => '2025-02-15',
                'end' => '2025-02-28',
                'progress' => 0,
                'dependencies' => '4008',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4007',
            ],

            // Stage: CONSTRUCTION
            [
                'id' => '4010',
                'name' => 'CONSTRUCTION',
                'start' => '2025-03-01',
                'end' => '2025-06-30',
                'dependencies' => ['4009'],
                'children' => ['4011', '4012', '4013'],
                'display' => true,
                'project_id' => '5',
                'important' => true,
            ],
            [
                'id' => '4011',
                'name' => 'Site Preparation',
                'start' => '2025-03-01',
                'end' => '2025-03-10',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4010',
            ],
            [
                'id' => '4012',
                'name' => 'Building Construction',
                'start' => '2025-03-11',
                'end' => '2025-06-15',
                'progress' => 0,
                'dependencies' => '4011',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4010',
            ],
            [
                'id' => '4013',
                'name' => 'Interior Setup',
                'start' => '2025-06-16',
                'end' => '2025-06-30',
                'progress' => 0,
                'dependencies' => '4012',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4010',
            ],

            // Stage: OPENING
            [
                'id' => '4014',
                'name' => 'OPENING',
                'start' => '2025-07-01',
                'end' => '2025-07-05',
                'dependencies' => ['4013'],
                'children' => ['4015', '4016'],
                'display' => true,
                'project_id' => '5',
                'important' => true,
            ],
            [
                'id' => '4015',
                'name' => 'Pre-opening Inspection',
                'start' => '2025-07-01',
                'end' => '2025-07-02',
                'progress' => 0,
                'dependencies' => '',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4014',
            ],
            [
                'id' => '4016',
                'name' => 'Grand Opening',
                'start' => '2025-07-03',
                'end' => '2025-07-05',
                'progress' => 0,
                'dependencies' => '4015',
                'display' => true,
                'project_id' => '5',
                'stage_id' => '4014',
            ],
        ];

        return Inertia::render('Dashboard', [
            'projects' => $projects,
            'tasks' => $tasks,
        ]);
    }
}
